### ISSUE TITLE
KeyNumber.String() broke for go 1.14

### ISSUE THREAD

**Issue by rbUUbr** [olivere/elastic#1304] opened 2020-04-01 14:09 UTC
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

Hi! Great library! I'm using nested aggregation together with  terms aggregation. I've just upgraded go to 1.14 and find out that `AggregationBucketKeyItem` returns empty string for aggregated keys in KeyNumber field
### Please describe the expected behavior
Get same data in KeyNumber field that I have in Key field
### Please describe the actual behavior
I'm getting "" in KeyNumber field, but I have actual data in Key field
### Any steps to reproduce the behavior?
aggregation function
```go
	myAggregation := elastic.NewNestedAggregation().Path("tags").SubAggregation(
		"tags",
		elastic.NewTermsAggregation().Field("tags.name").Size(20))
	service := elastic.Client.
		Search().
		Index("tags").
		Aggregation("tags", myAggregation).
		Query(elastic.NewBoolQuery())
```

transformation function:
```go
	aggregation, found := searchResult.Aggregations.Nested("tags")
	if found {
		tagsResult, found := aggregation.Terms("tags")
		if found {
			bucketsCount := len(tagsResult.Buckets)
			result := make([]*models.TagCompanyGroup, bucketsCount)
			for i, b := range tagsResult.Buckets {
				//key := b.Key.(string)
				result[i] = &models.MyCustomTag{
					Tag: &models.Tag{
						Slug: b.KeyNumber.String(), // doesn't work with go 1.14
					},
					Key:            b.KeyNumber.String(), // doesn't work with go 1.14
					Count: b.DocCount,
				}
			}
			return result, nil
		}
	}
```

**Comment by olivere** [comment] 2020-04-09 06:51
Thanks for letting me know. It seems weird that Go would change the behaviour of its `encoding/json` package. Can you post the HTTP response from ES as well? I need to come up with a reproducible test case so that we can illustrate the problem, fix it, and keep it fixed in future versions.

**Comment by olivere** [comment] 2020-05-01 13:23
It seems to be somehow related to the change [mentioned here in the Go 1.14 release notes](https://golang.org/doc/go1.14#encoding/json). The issue is https://github.com/golang/go/issues/37515, thoroughly discussed in https://github.com/golang/go/issues/37308 (https://github.com/golang/go/issues/14702).

It seems to me that the response doesn't return a valid number, in Go's sense. So waiting for sample output to create a reproducible test case.

**Comment by rbUUbr** [comment] 2020-05-05 14:10
Hey there! sorry for long response time :( 
here is the example:
request
```json
# nested aggregation
POST my-index/_search/
{
  "size": 0, 
  "aggs": {
    "tags": {
      "nested": {
        "path": "tags"
      },
      "aggs": {
        "tags": {
          "terms": {
            "field": "tags.name.keyword",
            "size": 10
          }
        }
      }
    }
  }
}
```
response
```json
{
  "took" : 38,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 3,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "tags" : {
      "doc_count" : 419652,
      "tags" : {
        "doc_count_error_upper_bound" : 3115,
        "sum_other_doc_count" : 281277,
        "buckets" : [
          {
            "key" : "tag1",
            "doc_count" : 33333
          },
          {
            "key" : "tag2",
            "doc_count" : 4444
          },
          {
            "key" : "tag3",
            "doc_count" : 1000
          },
          {
            "key" : "tag4",
            "doc_count" : 950
          },
          {
            "key" : "tag5",
            "doc_count" : 900
          },
          {
            "key" : "tag6",
            "doc_count" : 800
          },
          {
            "key" : "tag7",
            "doc_count" : 700
          },
          {
            "key" : "tag8",
            "doc_count" : 600 
          },
          {
            "key" : "tag9",
            "doc_count" :500
          },
          {
            "key" : "tag10",
            "doc_count" : 400
          }
        ]
      }
    }
  }
}

```

**Comment by olivere** [comment] 2020-06-06 17:40
I still cannot reproduce. I've written a test that checks various things about this issue, but I cannot get it to fail.

Please review https://github.com/olivere/elastic/blob/3db0060fd8cb964465de85d8062407472d6b8f46/search_aggs_bucket_terms_integration_test.go and change it so that it illustrates your point.

Will reopen then.

**Closed as completed by olivere** 2020-06-06 17:40 UTC
Labels: bug
