### ISSUE TITLE
Ability to slice without scrolling

### ISSUE THREAD

**Issue by Rmaan** [olivere/elastic#1633] opened 2022-07-20 14:57 UTC
### Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
As scrolling is deprecated in Elasticsearch, I'm trying to do a point-in-time search and want to use slicing like [this example in docs](https://www.elastic.co/guide/en/elasticsearch//reference/8.3/point-in-time-api.html#search-slicing).

But `SearchService` class has no way to set the slice. And if I use `ScrollService` there's no way to set a point-in-time, obviously.

Am I missing something or this functionality is absent?

**Comment by olivere** [comment] 2022-07-20 15:21
Yes, it's missing. Probably a duplicate of #1575, right?

**Comment by Rmaan** [comment] 2022-07-20 15:27
Thanks for quick response.

I just wanted to have the low level support (i.e. supporting `scroll` in a normal search API call), if there's a high level service as well it should be enough.

Should I close this one then?

**Comment by olivere** [comment] 2022-07-20 15:39
For low-level support, there must an API to work with PITs. Those can then be passed on to the scroll service. There might be a high-level service once that does this out-of-the-box. But I can't promise anything. Let's discuss this in the scope of #1575.

**Closed as completed by olivere** 2022-07-20 15:39 UTC
