### ISSUE TITLE
 invalid memory address or nil pointer dereference goroutine

### ISSUE THREAD

**Issue by ishare** [olivere/elastic#77] opened 2015-05-26 15:40 UTC
I use go-workers, and some times I meet some problems like this, could you help me ?

JID-38fe0021c6a213377cee972d error: runtime error: invalid memory address or nil pointer dereference
goroutine 99 [running]:
github.com/jrallison/go-workers.func·007()
	/root/.jenkins/jobs/chitu/workspace/go/src/github.com/jrallison/go-workers/middleware_logging.go:23 +0x280
github.com/jrallison/go-workers.func·008()
	/root/.jenkins/jobs/chitu/workspace/go/src/github.com/jrallison/go-workers/middleware_retry.go:43 +0x566
github.com/jrallison/go-workers.func·009()
	/root/.jenkins/jobs/chitu/workspace/go/src/github.com/jrallison/go-workers/middleware_stats.go:13 +0x74
github.com/olivere/elastic.(*Client).PerformRequest(0x0, 0xa92c80, 0x3, 0xc208467300, 0x13, 0xc208473b30, 0xa44f80, 0xc2080b57a0, 0x0, 0x0, ...)
	/root/.jenkins/jobs/chitu/workspace/go/src/github.com/olivere/elastic/client.go:785 +0xec5
github.com/olivere/elastic.(*IndexService).Do(0xc2080b5880, 0xa44f80, 0x0, 0x0)
	/root/.jenkins/jobs/chitu/workspace/go/src/github.com/olivere/elastic/index.go:206 +0xfba

**Comment by olivere** [comment] 2015-05-26 15:49
Hmm... it seems like the `Client` is `nil`. But I'm not sure how this can happen without more details. How do you manage an `elastic.Client` entity, how and when do you create it, do you destroy it (and if so, how?) etc.

**Comment by olivere** [comment] 2015-05-28 13:03
Closing this now. Feel free to open a new issue if the problem remains and the problem is related to Elastic.

**Closed by olivere** 2015-05-28 13:03 UTC
