### ISSUE TITLE
span queries

### ISSUE THREAD

**Issue by pzentenoe** [olivere/elastic#1337] opened 2020-06-01 20:45 UTC
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I need to use span queries

### Please describe the actual behavior
does not exist near query and anothers span queries 
when could you add them?

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-span-near-query.html

**Comment by olivere** [comment] 2020-06-02 16:33
This is a duplicate of https://github.com/olivere/elastic/issues/1284. At the moment, we don't have these queries, but you can build them yourself and pass them as a `RawStringQuery`.

**Closed as completed by olivere** 2020-06-02 16:33 UTC

**Comment by pzentenoe** [comment] 2020-06-02 19:30
I added span near query for need of use. you could check if it is feasible to upload this and generate a new olivere release
https://github.com/olivere/elastic/issues/1337

**Comment by pzentenoe** [comment] 2020-06-02 19:31
Can you review
