### ISSUE TITLE
Elasticsearch 7: hits.total is an object in the search response

### ISSUE THREAD

**Issue by praseodym** [olivere/elastic#1007] opened 2019-01-09 20:09 UTC
In Elasticsearch 7, [`hits.total` is an object in the search response](https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-7.0.html#_literal_hits_total_literal_is_now_an_object_in_the_search_response). This breaks searches in the current version of the library with an unmarshalling error: `
json: cannot unmarshal object into Go struct field SearchHits.total of type int64`.

There is a request parameter (`rest_total_hits_as_int=true`) that can be added to get back the old behaviour, but I don't think this library currently has an easy way of adding this parameter to requests.

**Comment by olivere** [comment] 2019-01-09 21:18
Oh, there are probably hundreds of issues with Elasticsearch 7. I still have to work on support for v7. Elastic currently doesn’t support 7.x as of writing this.

**Comment by olivere** [comment] 2019-01-15 11:04
I will close this now. It will very likely be caught when preparing for the v7 release anyway.

**Closed by olivere** 2019-01-15 11:04 UTC

**Comment by Abillions** [comment] 2019-07-30 12:24
I have the problem same as above ,so how to solve it now?

**Comment by olivere** [comment] 2019-07-30 15:04
@jamesunvin You need to use elastic.v7 with ES 7.x and elastic.v6 with ES 6.x, then everything will work as expected.

**Comment by praseodym** [comment] 2019-08-04 13:41
It's a bit unfortunate that this is currently a breaking change. By adding the `rest_total_hits_as_int=true` request parameter the elastic.v6 library should with Elasticsearch 7 just fine, which makes it possible to do upgrades without application downtime.

**Comment by olivere** [comment] 2019-08-05 09:01
@praseodym May I ask why this would help you? Although I haven't looked into this in detail, `rest_total_hits_as_int` is a parameter for ES 7.x. If you use ES 7.x, you can simply use the new struct returned by ES 7.x, and that works perfectly with elastic.v7.

You know, elastic.v6 is meant to be used with ES 6.x, and elastic.v7 is meant to to be used with ES 7.x. What is not supported is using elastic.v6 with ES 7.x.

**Comment by praseodym** [comment] 2019-08-05 15:23
@olivere This would allow non-breaking upgrades to ES 7.x. Elasticsearch itself supports rolling upgrades without downtime, but that does require applications to make forwards-compatible requests, i.e. by requesting ES 7.x to fall back to old (deprecated) behaviour, or these applications will break.

`rest_total_hits_as_int` is supported in recent ES 6.x releases (where it gets ignored) so that the same request can be made to an ES 7.x server, which will then return the same response as the 6.x server would. The application can then be upgraded to support the new format (i.e. upgrading to elastic.v7) at a later time.

Furthermore, during a rolling upgrade the cluster is in a mixed-version state running both ES 6.x and 7.x, so upgrading the application to expect the 7.x response format at that time will break for requests made against 6.x servers.

**Comment by olivere** [comment] 2019-08-05 16:16
That makes sense, of course. Thanks for clarifying.

Sorry for being so pedantic. I've been bitten so many times by incompatible und undocumented changes between major ES versions that I've decided, long ago, to keep parity between elastic.vN and ES N.x (where  `N >= 5`). I've [added that parameter to elastic.v6](432e9876f6f564b1674252758fc257c6f6cecf5e) in 6.2.22 (just cutting the release), but I just can't support all those people that will now start asking why they can't use feature X from ES 7.x in elastic.v6.

**Comment by laizhenxing** [comment] 2019-09-02 15:33
I use ES 6.7.0 and the elastic.v6, but I still have this problem(`json: cannot unmarshal number into Go struct field SearchHits.total of type elastic.TotalHits`)

**Comment by olivere** [comment] 2019-09-02 16:20
@laizhenxing The error message indicates that Go tries to unmarshal a numerical value in JSON value `SearchHits.total` into a type `elastic.TotalHits`. In v6, [`SearchHits.total` is of type `int64`](https://github.com/olivere/elastic/blob/release-branch.v6/search.go#L529). In v7, [`SearchHits.total` is of type `*elastic.TotalHits`](https://github.com/olivere/elastic/blob/release-branch.v7/search.go#L526). So you somehow _are_ using elastic.v7, not elastic.v6.

**Comment by laizhenxing** [comment] 2019-09-02 16:29
> @laizhenxing The error message indicates that Go tries to unmarshal a numerical value in JSON value `SearchHits.total` into a type `elastic.TotalHits`. In v6, [`SearchHits.total` is of type `int64`](https://github.com/olivere/elastic/blob/release-branch.v6/search.go#L529). In v7, [`SearchHits.total` is of type `*elastic.TotalHits`](https://github.com/olivere/elastic/blob/release-branch.v7/search.go#L526). So you somehow _are_ using elastic.v7, not elastic.v6.

ok, thanks a lot

**Comment by audreychoyy** [comment] 2019-10-06 22:36
@olivere  
Hi, I run into the same issue. The error message is "Failed to read post from ElasticSearch json: cannot unmarshal number into Go struct field SearchHits.total of type elastic.TotalHits"
I verify that my ES version is 6.8.3.
And I import your elastic.v6 by "go get github.com/olivere/elastic" and import "github.com/olivere/elastic".
Could you give me some insights? Thanks!

**Comment by olivere** [comment] 2019-10-07 04:40
@zixincai Please use the correct version for your ES server, see https://github.com/olivere/elastic/blob/release-branch.v7/README.md#releases

**Comment by panguicai008** [comment] 2020-06-15 05:19
"json: cannot unmarshal number into Go struct field **SearchHits.hits.total** of type elastic.TotalHits " is same as "json: cannot unmarshal number into Go struct field **SearchHits.total** of type elastic.TotalHits" ?

**Comment by guettli** [comment] 2020-07-16 07:57
@panguicai008 the maintainer of this package already added support for `rest_total_hits_as_int=true` in the v6 branch. This way the v6 version of `elastic` can be used with ES 7 (for rolling upgrade: first the server 6 --> 7, then the clients). Please upgrade to the latest v6 version of `elastic`. If the error still occurs, please check if you can provide a pull request. Thank you.

**Comment by udit4** [comment] 2020-08-25 14:07
Thanks @olivere for adding the support, much appreciated ..

**Comment by jgimenez** [comment] 2020-10-15 15:51
I'm still hitting this error when using the scroll service. Would you accept a PR?

**Comment by olivere** [comment] 2020-10-15 17:30
@jgimenez Sure. But we should make sure what the issue is, otherwise we might find out that a PR wasn't necessary in the first place.

**Comment by jgimenez** [comment] 2020-10-15 21:27
The issue is that the `ScrollService` struct does not have a `RestTotalHitsAsInt()` function like the one introduced for the `SearchService`, so it's not possible to online migrate between ES 6 and 7 using the v6 branch.

**Comment by olivere** [comment] 2020-10-16 14:31
@jgimenez I see. https://github.com/olivere/elastic/commit/40e4e98362590a34c09b61ad82ffd57bcb7aec68 should do the trick. Hope to release it soon.

**Comment by jgimenez** [comment] 2020-10-16 15:22
Awesome, thanks!

**Comment by behos** [comment] 2020-11-19 08:50
Hi @olivere , is there a plan to release this on the v6 branches as well? To do an online migration we need this functionality in v6 but it's currently relased on v7 from what I can see. :)
