### ISSUE TITLE
Unclosed sockets

### ISSUE THREAD

**Issue by swizzley** [olivere/elastic#619] opened 2017-10-08 15:17 UTC
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
socket starts as SYN_SENT, is then ack'd and then changes to ESTABLISHED

`lsof -i tcp`
```
elasticclient    16175 root  686u  IPv4 658186542      0t0  TCP localhost:59201->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  687u  IPv4 658188424      0t0  TCP localhost:59203->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  688u  IPv4 658181105      0t0  TCP localhost:59205->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  689u  IPv4 658184884      0t0  TCP localhost:59208->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  694u  IPv4 658188425      0t0  TCP localhost:59229->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  695u  IPv4 658186543      0t0  TCP localhost:59237->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  696u  IPv4 658187512      0t0  TCP localhost:59241->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  697u  IPv4 658184886      0t0  TCP localhost:59246->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  700u  IPv4 658181107      0t0  TCP localhost:59261->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  703u  IPv4 658184887      0t0  TCP localhost:59274->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  704u  IPv4 658185818      0t0  TCP localhost:59279->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  707u  IPv4 658184888      0t0  TCP localhost:59287->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  712u  IPv4 658184889      0t0  TCP localhost:59323->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  713u  IPv4 658185820      0t0  TCP localhost:59324->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  714u  IPv4 658181109      0t0  TCP localhost:59331->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  715u  IPv4 658188428      0t0  TCP localhost:59333->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  720u  IPv4 658181110      0t0  TCP localhost:59342->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  721u  IPv4 658185822      0t0  TCP localhost:59346->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  724u  IPv4 658188430      0t0  TCP localhost:59359->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  725u  IPv4 658181111      0t0  TCP localhost:59361->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  726u  IPv4 658185823      0t0  TCP localhost:59365->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  727u  IPv4 658184892      0t0  TCP localhost:59373->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  734u  IPv4 658187517      0t0  TCP localhost:59395->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  735u  IPv4 658185825      0t0  TCP localhost:59399->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  737u  IPv4 658188432      0t0  TCP localhost:59403->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  739u  IPv4 658184894      0t0  TCP localhost:59415->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  740u  IPv4 658187518      0t0  TCP localhost:59417->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  741u  IPv4 658185826      0t0  TCP localhost:59418->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  748u  IPv4 658186551      0t0  TCP localhost:59472->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  749u  IPv4 658181115      0t0  TCP localhost:59474->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  750u  IPv4 658188434      0t0  TCP localhost:59476->localhost:wap-wsp (SYN_SENT)
elasticclient    16175 root  751u  IPv4 658184896      0t0  TCP localhost:59478->localhost:wap-wsp (SYN_SENT)
```
### Please describe the actual behavior
overtime, usually several hours of sustained requests ~100 read requests per minute, with ~12 write requests per second, on a single local node, sockets get left open and the service load of the client increases exponentially

### Any steps to reproduce the behavior?
it reproduces consistently, the problem is I don't know if it's server side or client side creating the problems, there is nothing what so ever in the elastic log to be useful except maybe for this:
```
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.retryBecauseUnavailable(TransportReplicationAction.java:614)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:474)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onTimeout(TransportReplicationAction.java:576)
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:236)
	at org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(InternalClusterService.java:816)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	^Cat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Absolutely any help or insight would be greatly appreciated.

**Comment by swizzley** [comment] 2017-10-09 18:21
Go: 1.9
OS: CentOS 7.1 (3.10.0-514.16.1.el7.x86_64)
On Premises... 
Elastic 2.4.5-1

Most of the sample code was cut/paste from the elastic documentation

```
elasticClient, err := elastic.NewClient(
		elastic.SetURL(elasticHost),
		elastic.SetSniff(false),
		elastic.SetHealthcheckInterval(12*time.Second))
	if err != nil {
		fmt.Println("{ \"ERROR\": \"elastic client\" }")
		<-e
		return snapshot, err
	}
```

**Comment by olivere** [comment] 2017-10-09 18:27
Does [running this in an endless `for { ... }` loop](https://github.com/olivere/elastic/blob/release-branch.v5/recipes/connect/connect.go) yield the same results over time?

**Comment by swizzley** [comment] 2017-10-09 19:41
it crashes instantly after 1 success

```
 go run main.go 
Connection succeeded
/tmp/go-build268810970/command-line-arguments/_obj/exe/main flag redefined: url
panic: /tmp/go-build268810970/command-line-arguments/_obj/exe/main flag redefined: url

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420064060, 0x827320, 0xc420138120, 0x6e1868, 0x3, 0x6e4890, 0x11)
	/usr/local/go/src/flag/flag.go:793 +0x5e1
flag.(*FlagSet).StringVar(0xc420064060, 0xc420138120, 0x6e1868, 0x3, 0x6e5f77, 0x15, 0x6e4890, 0x11)
	/usr/local/go/src/flag/flag.go:696 +0x8b
flag.(*FlagSet).String(0xc420064060, 0x6e1868, 0x3, 0x6e5f77, 0x15, 0x6e4890, 0x11, 0x0)
	/usr/local/go/src/flag/flag.go:709 +0x8b
flag.String(0x6e1868, 0x3, 0x6e5f77, 0x15, 0x6e4890, 0x11, 0xc420010b30)
	/usr/local/go/src/flag/flag.go:716 +0x69
main.main()
	/home/dmorgan/elasticdebug/main.go:25 +0xc6
exit status 2
```

all I did was add `for`

```
func main() {
for {
	var (
		url   = flag.String("url", "http://localhost:9200", "Elasticsearch URL")
		sniff = flag.Bool("sniff", true, "Enable or disable sniffing")
	)
	flag.Parse()
	log.SetFlags(0)

	if *url == "" {
		*url = "http://127.0.0.1:9200"
	}

	// Create an Elasticsearch client
	client, err := elastic.NewClient(elastic.SetURL(*url), elastic.SetSniff(*sniff))
	if err != nil {
		log.Fatal(err)
	}
	_ = client

	// Just a status message
	fmt.Println("Connection succeeded")
   }
}
```

**Comment by olivere** [comment] 2017-10-09 20:40
You're re-defining the flags, that's what the error says.

Please try something like this:

```
// Copyright 2012-present Oliver Eilhard. All rights reserved.
// Use of this source code is governed by a MIT-license.
// See http://olivere.mit-license.org/license.txt for details.

// Connect simply connects to Elasticsearch.
//
// Example
//
//
//     connect -url=http://127.0.0.1:9200 -sniff=false
//
package main

import (
	"flag"
	"log"
	"time"

	"gopkg.in/olivere/elastic.v5"
)

func main() {
	var (
		url   = flag.String("url", "http://localhost:9200", "Elasticsearch URL")
		sniff = flag.Bool("sniff", true, "Enable or disable sniffing")
		sleep = flag.Duration("sleep", 1*time.Second, "Sleep interval")
	)
	flag.Parse()
	log.SetFlags(0)

	if *url == "" {
		*url = "http://127.0.0.1:9200"
	}

	// Create an Elasticsearch client
	client, err := elastic.NewClient(elastic.SetURL(*url), elastic.SetSniff(*sniff))
	if err != nil {
		log.Fatal(err)
	}

	var n int
	for {
		n++
		log.Printf("Ping %06d", n)
		client.IndexExists("some-index")
		time.Sleep(*sleep)
	}
}
```

**Comment by swizzley** [comment] 2017-10-10 13:29
Okay, interesting results...
The ping never crashed. However for the first time, the application did. 
```
Ping 037775
Ping 037776
Ping 037777
Ping 037778
Ping 037779
Ping 037780
Ping 037781
Ping 037782
Ping 037783
```
This is the panic...
```
Post http://127.0.0.1:9200/_search/scroll: dial tcp 127.0.0.1:9200: socket: too many open files
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6594ad]
```

**Comment by olivere** [comment] 2017-10-10 13:57
To me it looks like you're running out of resources. How are you using the client? Are you creating a new client every time (which you shouldn't)? Are you properly closing resources (like closing the HTTP response body so that the connection will be released eventually)?

I'm sorry but I'm unable to help you without access to the source code. You need to find a way to make it reproducible to pin it down to a problem in Elastic, not somewhere else in your application.

**Comment by olivere** [comment] 2017-10-10 13:58
As to the example above: There is no call to `/_search/scroll`. How can the ping example above supposed to crash without ever calling that?

**Comment by swizzley** [comment] 2017-10-10 15:33
The call to `/_search/scroll` is within the application having the issue. However I think this is moot since your previous comment seems to me to explain the entire issue. At present the source code creates a new client upon every new search request. Although, your question about closing the response body is slightly disconcerting since even in your Ping snippit, I don't recognize any example of this. If you're asking about whether I am in general, the answer is yes, for loading data into elasticsearch, I don't use the `elastic.NewClient` I simply use a net/http POST for which I am in fact closing the response for. If that is what your question is pertaining to, then the answer is yes, and I feel with a few edits to share the `elastic.NewClient` instead of creating one each time, this issue should be resolved. I am wondering though, for instances when NewClient fails, is there a method for testing this directly before passing it along? I ask because the source runs in an infinite loop, and NewClient is a dependent of several objects within that loop, and my fear is that if the client is created prior to entering the infinite loop, and then later at some point, fails, I feel like there should be a check to validate a usable client, else create it again, but currently the only check seems to be the err returned when actually creating the new client. Any thoughts or suggestions?

**Comment by swizzley** [comment] 2017-10-10 15:47
Actually, I just found the `NewSimpleClient` which I feel is perfectly suited for my needs here. This makes sense now, thank you for the help.

**Comment by swizzley** [comment] 2017-10-10 15:56
Also, I just found in the wiki, a most important line `defer elasticClient.Stop()` I am not sure if the wiki differs from the godoc that much, but I feel like I cut/paste from the godoc originally, and not the wiki.

**Comment by olivere** [comment] 2017-10-10 17:36
You typically create one `*elastic.Client` at startup, in the `main`, then pass it on to the part of the applications that require it. An `*elastic.Client` is safe to use from different threads/goroutines, so you can share it between different parts of your application and still just use one client only. If you create only one client in the main, it's also not necessary to stop it, as it will automatically stop when `main` is done.

Most applications that I see recently, especially since the microservices movement set in a few years ago, wire up things in the `main`. Dependencies satisfy an interface and are instantiated in `main`, then passed down to the different parts of the application/service. Creating applications this way also significantly helps testing, as you mock the different dependencies.

Wrt the statement about closing HTTP requests: I asked this because that's something that would perfectly describe the errors you see (too many open files etc.). In other words: Even if Elastic *did* close all HTTP response bodies properly, it could be *your* code not closing them properly, and still yield the same error.

Re `NewClient` vs `NewSimpleClient`: The former is good for a long-running application and should survive even if you add or remove nodes from your ES cluster. The latter is basically a simple "throwaway" client where you only want to shoot out a HTTP request to ES from time to time.

Anyway. HTH.

**Closed by olivere** 2017-10-10 17:36 UTC

**Comment by swizzley** [comment] 2017-10-10 19:11
Thank you very much for the insight and background. The sockets appear much more stable now, and are not ballooning up to huge numbers as before.

**Comment by wupeaking** [comment] 2017-10-13 03:42
@swizzley  
Hi，My English is poor. There was a similar problem when I did stress tests. Then I analyzed the flame map.   I find ` (* Client) .healthcheck.func1 and healthchecker` takes up a lot of CPU usage. 
So I think The main reason is because the health check is turned on.

**Comment by swizzley** [comment] 2017-10-13 15:08
@wupeaking that may or may not be the case, I don't know. But, I am fairly certain that `healthcheck` is a parameter you can set to `false` which when using the `NewSimpleClient` is the case by default, and using this client is what has resolved my issue.

**Comment by olivere** [comment] 2017-10-13 15:15
@swizzley @wupeaking I'm unable to see how [healthchecker](https://github.com/olivere/elastic/wiki/Healthcheck) can take up a lot of CPU. It's basically [running a HTTP HEAD request every 60 seconds by default](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L1015-L1076). Can you send a reproducible example of your problem?

Even if you find it unreliable, you can [tweak all of its properties](https://github.com/olivere/elastic/wiki/Configuration) and get a client that has a chance of finding and reviving unhealthy nodes.

**Comment by swizzley** [comment] 2017-10-14 03:41
My issue is resolved, and it didn't have anything to do with health checks as far as I know. My issue was I was creating multiple clients, and not closing them.

**Comment by wupeaking** [comment] 2017-10-18 08:49
@olivere  @swizzley  I think my question is similar to @swizzley . I also create multiple clients for every http request. I expect these clients to be released automatically, But because of the reasons for health checks, resulting in these clients will not be released. As http requests more and more, it creates a large number of clients and then has a large number of health checks exist. This will increase the CPU usage.

**Comment by olivere** [comment] 2017-10-18 09:07
This is probably the most common source of confusion in Elastic. You typically create just one `*Client` with `elastic.NewClient(...)`, then use it everywhere. The `NewClient` spins up a bunch of goroutines to do health checks and sniffing. If you create a new client for every request, you spin up hundreds or even thousands of goroutines.

If you want a single "throwaway" client, use `elastic.NewSimpleClient`.

So why do you have `NewClient` at all? What are the benefits? Some even dissed me over why I'm so stupid to even do something like this. The two main reasons are:

1. All official clients do that (*): [Ruby](http://www.rubydoc.info/gems/elasticsearch-transport#Reloading_Hosts), [Python](https://elasticsearch-py.readthedocs.io/en/master/#thread-safety) etc.
2. The health checks and sniffing try to help you handle exceptional cases in your cluster. If you add a new node to your cluster, sniffing should automatically find and use it. If you remove a node, it will stop sending requests to it. If a node isn't responding, it is marked as unhealthy. If it becomes healthy again, it will receive requests again. You have to do all of this in your own code with `NewSimpleClient`.

(*) The Python client changed the defaults recently in that it doesn't sniff by default now. The Ruby client still has this turned on AFAIK. Elastic can only change those defaults in major versions because it's a breaking change. But I consider doing that in 6.0.

**Comment by wupeaking** [comment] 2017-10-19 02:38
I think your design is very good. But when we first use this package, we will generally follow the example of the code, will not notice this problem. If you can explain this in the document, it will be perfect. 😝
