### ISSUE TITLE
Not all requests use POST instead of GET

### ISSUE THREAD

**Issue by gdm85** [olivere/elastic#170] opened 2015-11-25 10:38 UTC
I just noticed #167, nice feature addition, however I am not sure this is complete.

I noticed that calls for settings, aliases for example are not using it:
```
GET http://localhost:9200/_all/_settings [status:200, request:0.033s]
elastic: http://localhost:9200 is dead
time="2015-11-25T11:32:47+01:00" level=fatal msg="Get http://localhost:9200/[>4096 bytes omissis]/_aliases: EOF"
```

This in turn makes the `elastic.SetSendGetBodyAs("POST")` less effective.

**Comment by olivere** [comment] 2015-11-25 10:56
Can you explain exactly what you do to retrieve settings/aliases (so I can try to reproduce where this happens)?

**Comment by gdm85** [comment] 2015-11-25 18:23
Pretty sure it's a call to `client.Aliases()`, however I can report this back in about 40 hours

**Comment by olivere** [comment] 2015-11-25 19:07
Didn't have time to look into it. But all calls with GET and a body should be changed to POST in Client.PerformRequest. However, GET calls *without* a body will still use GET!

**Comment by gdm85** [comment] 2015-11-27 08:39
@olivere you're right, I am afraid this is a type of query that doesn't benefit from using GET with body.

The only way one could workaround the issue here is making multiple calls to make sure the URI stays below 4096 bytes (the default for ES' natty), then merge the results.

Would you likely accept a PR adding a feature like this? I would start specifically from this call and check if others need it to.

Pros:
* if you have load balancers/proxy you want to stay below a specific (standard-friendly) amount of bytes for your GET requests URIs
Cons:
* for loops in the code when request URI is too long, makes code a tad less elegant probably

**Comment by olivere** [comment] 2015-11-27 08:45
I'm afraid I probably don't understand the root issue yet. Can you elaborate?

From the perspective of a client, I'd like to stay within the limits of the official clients. If you e.g. find a behavior in the official clients for Ruby, Python, Perl etc. and elastic behaves different, I'm very likely willing to change that. But I'm probably not moving to far off track. E.g. elastic should always be "just a client", not some sort of "do-it-all" library. I hope the explanation will give you an idea :-)

**Comment by olivere** [comment] 2015-11-27 08:53
@gdm85 It looks like you have problems with maximum length of the URL, do you? Can you can increase [`http.max_initial_line_length`](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) in your cluster?

**Comment by gdm85** [comment] 2015-11-27 09:26
@olivere sure, however if you have multiple hops (think about proxies/load-balancers) then it becomes a bit cumbersome to change all of them (of course all of them have a setting to set the max request, although their defaults might vary), plus it might not anyway be a good idea to have GET calls >4k being logged.

This SO answer is helpful on the topic: http://stackoverflow.com/a/266341

The root of the problem here is that ES itself it's not returning 414 but a 50x instead, but to stay within the scope of this client library I was thinking something along these lines:
```
    var get_uri string
    // ...
    get_uri = 'http://localhost:9200/index_a,index_b,index_c/_aliases
    if len(get_uri)>4000 {
         // ... split aliases call and combine results
    }
```

This would workaround the error; you are to tell if it's a viable feature to have in the library :)

**Comment by olivere** [comment] 2015-11-27 09:35
@gdm85 I think solving this at the ES client library level is the wrong place. It is a network/infrastructure concern.

**Comment by gdm85** [comment] 2015-11-27 09:46
@olivere well, the client library is right now able to generate GET requests that are beyond the average max GET request size of all widely available webservers; the only way one can mitigate this is changing server configurations (but it can't be changed to `+inf` anyway) or by grouping multiple calls and aggregating requests (that would be a client library feature).

**Comment by olivere** [comment] 2015-11-27 16:52
@gdm85 So you're arguing that elastic should fix its behavior because it might generate URLs that are incomprehensible by some web servers/proxies? I don't think that's the right way to go. You could as well argue that net/http, which elastic uses under the hood, generates invalid URLs.

Anyway... if you still want to get your hands on it, feel free to copy `aliases.go` and tweak it accordingly. The services all basically rely on `PerformRequest` in `client.go`. `PerformRequest` is exported and you should be able to use it in your own "elastic-contrib" package.

**Comment by gdm85** [comment] 2015-11-30 14:05
@olivere `net/http` generates URL for anything, while `elastic` for a specific server for the purpose of fulfilling those requests successfully. I am just saying that by regular usage of this client library, you can have perfectly valid data in ES yet be unable to access it depending on completely legit configurations of the webservers between you and the data (increasing the request length is not always viable/desired).

I was just proposing what needs to be changed in case anybody wants to make this client library work with any ES cluster dataset and an average/default configured ES/webserver/proxy :)

**Comment by gdm85** [comment] 2015-11-30 15:56
By the way, Amazon's ES service is also limited this way, so people might not be able to use it with that (although they can ask Amazon to ramp up the 4096 default too).

**Comment by gdm85** [comment] 2015-12-01 08:16
For the records (and help of future readers), this is the workaround I have put in place.
```
func getIndicesByAlias(client *elastic.Client, aliasName string, indices []string) ([]string, error) {
	var aliasIndices []string

	/*	// {
		//   "indexName" : {
		//     "aliases" : {
		//       "alias1" : { },
		//       "alias2" : { }
		//     }
		//   },
		//   "indexName2" : {
		//     ...
		//   },
		// }*/

	for _, indexToLookup := range indices {
		result, err := client.Aliases().Indices(indexToLookup).Do()
		if err != nil {
			return nil, err
		}

		for indexName, indexInfo := range result.Indices {
			for _, aliasInfo := range indexInfo.Aliases {
				if aliasInfo.AliasName == aliasName {
					aliasIndices = append(aliasIndices, indexName)
				}
			}
		}
	}

	return aliasIndices, nil
}
```

So rather simple in the end :) It replaces the corresponding function in elastic.

**Comment by olivere** [comment] 2015-12-01 08:19
That's very helpful. I will at least add it to the Wiki, maybe add a method to the client (there already is a helper called `IndexNames`). Thanks.

**Comment by gdm85** [comment] 2015-12-01 19:05
@olivere I am using a modified version of the above function where I first get all the indices with another call, so that the `indices` func argument is unnecessary (as it would scan through all indices); I'll leave to you which version is best :)

Basically it's an alternative to `IndicesByAlias` as defined in `aliases.go`, that I can't use because of the problem in OP.

Off-topic, but I have noticed that using `SetHttpClient` is really a good idea with many workers to limit the amount of open connections; I have added a change [here](https://github.com/olivere/elastic/wiki/Configuration/_compare/ceb2b7337b169a7a2e7f6bea1ab179c56099abb6...7b8cbfc6808724427c32211f20b1a1d3f7517e1d), feel free to review/put it in another page.

**Comment by olivere** [comment] 2015-12-02 08:01
@gdm85 I will have another look at the `IndexNamesByAlias` topic when I've got some leisure time.

Regarding the TCP connections: IIRC Go handles a pool of connections at the transport layer for you. If you use `http.DefaultClient` you should only get one transport hence only one pool of connections. I'd be concerned if you get too many TCP connections. Do you create more than one elastic Client in your application?

**Comment by gdm85** [comment] 2015-12-02 15:29
@olivere yeah that was the case, and by using a single `http.Client` the problem is solved (as now all my clients share the same HTTP client, which benefits from pooling).

**Comment by olivere** [comment] 2015-12-04 09:39
I decided to not add `IndexNamesByAlias` to the client but to add a page to the [Wiki](https://github.com/olivere/elastic/wiki/Listing-all-indices-of-an-alias) instead.

**Closed by olivere** 2015-12-04 09:39 UTC
