### ISSUE TITLE
run example code with elastic5.2.0 get " Fielddata is disabled on text fields by default"

### ISSUE THREAD

**Issue by superheizai** [olivere/elastic#458] opened 2017-02-12 05:18 UTC
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
setup 5.2.0 elasticserach, example code runs well.

### Please describe the actual behavior

use example code to demo and get the exception:
Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [user] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.

**Comment by superheizai** [comment] 2017-02-12 07:51
or this problem can be as a question, how to set the user, which is in Tweet struct in example, with fielddata as true

**Comment by olivere** [comment] 2017-02-13 09:30
Thanks for reporting. I fixed the example code on the [project site](https://olivere.github.io/elastic/) to work with Elasticsearch 5.x. It should be ready soon when GitHub synchronizes.

The problem is due to the fact that ES 5.x uses a recent version of Lucene under its covers. That Lucene version introduced new types for strings, namely `text` and `keyword`. The `string` type is gone in Lucene and only available in ES 5.x as a fallback, mapped as a multi-field like [stated here](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/breaking_50_mapping_changes.html#_literal_string_literal_fields_replaced_by_literal_text_literal_literal_keyword_literal_fields).

Furthermore, Elasticsearch 5.x introduced a new scripting language called `painless`. That changed scripting quite a bit, and it is fixed in the example on the project site now.

Are you referring to some other example code. If so, where did you find it?

The general problem with example code is that I cannot write code that is forward-compatible. E.g. the code in the README explicitly states it is written for elastic.v3 (which should work on Elasticsearch 2.x). The example code on the project site however used elastic.v5, so a fix was required.

**Closed by olivere** 2017-02-13 09:30 UTC

**Comment by olivere** [comment] 2017-02-13 09:31
BTW: If you need code that works all the time, use the one that is unit tested on every build, e.g. [`example_test.go`](https://github.com/olivere/elastic/blob/release-branch.v5/example_test.go).

**Comment by superheizai** [comment] 2017-02-14 01:50
thanks for your reply. but still with error for version v5 on this site: https://olivere.github.io/elastic/
1. need parameter for client.Ping(). There is one parameter,url, in Ping method, and with parameter in former version, but missed in current version.
2. need to comment "ScriptParams(map[string]interface{}{"num": 1}).", and which was done also in former version
3. when use termQuery, should be Query(termQuery), not Query(&termQuery)
4. useless import for "net/http"
5. get the exception. Cannot use "ctx._source.retweets += num" (type string) as type *elastic.Script in argument to client.Update().Index("twitter").Type("tweet").Id("1").Script

**Comment by olivere** [comment] 2017-02-14 09:56
You seem to still have the old version, maybe in cache. I already have the new version which fixes all the issues you listed, and some more. I ran it locally against 5.2.0.

GitHub generates the GitHub project sites on-demand. If you're interested, the project site is in the [`gh-pages` branch](https://github.com/olivere/elastic/tree/gh-pages).
