### ISSUE TITLE
Range queries produces with deprecated from/to syntax

### ISSUE THREAD

**Issue by pmalekn** [olivere/elastic#1269] opened 2020-01-10 13:37 UTC
### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

Package should produce range query with `gt`, `gte`, `lt`, `lte` etc. fields

### Please describe the actual behavior

Package produces range query with `from`, `to`, etc. 

A comment from elasticsearch repo mentioning that this was already deprecated in `0.90.4`
https://github.com/elastic/elasticsearch/issues/48538#issuecomment-552642795

and a related issue from 2016
https://github.com/olivere/elastic/issues/196

### Any steps to reproduce the behavior?

Create a range query with lower limit `.Gte()` or upper limit `.Lte()` and observe the produced source.

**Comment by olivere** [comment] 2020-01-10 22:45
Duplicate of #1187.

While it might be deprecated, it doesn't log a deprecation warning and is still [alive and kicking](https://github.com/elastic/elasticsearch/blob/7.5/server/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java#L321-L341), even in 7.5.

**Closed as completed by olivere** 2020-01-10 22:45 UTC
