### ISSUE TITLE
ScrollService.Do(ctx context.Context) takes lot more time than searchResult.TookInMillis

### ISSUE THREAD

**Issue by rohanil** [olivere/elastic#614] opened 2017-09-25 12:43 UTC
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Question
To search 50k search results using scroll API is taking around 1 sec. The scroll size is 10k so each query execution is taking around 200ms but it is much higher than `TookInMillis` in searchResult. SearchResult.TookInMillis is around 60ms so I don't know where exactly the time is taken. Total number of primary shards are 5 by default. Reducing scroll size from 10k to 5k, does not change anything from performance point of view. Is this expected behaviour?

And is ScrollService implemented with `search_type=scan`?

**Comment by olivere** [comment] 2017-09-25 19:47
@rohanil Can you create a reproducible test case? My initial guess is cost of JSON encoding/decoding. We use it extensively, so I'm not sure what happens.

The `search_type=scan` is deprecated since 2.1 and was [removed in 5.0](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/breaking_50_search_changes.html#_literal_search_type_scan_literal_removed).

**Comment by rohanil** [comment] 2017-09-26 12:51
Below is a test script with simple struct. It creates index if it does not exist then sends bulk request for indexing 60000 documents. And it scrolls over those 60000 documents to get 50000 as search result. The logs are after script.

```
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"strconv"
	"time"
	elastic "gopkg.in/olivere/elastic.v5"
)

// TestStruct is test structure
type TestStruct struct {
	Prop1 int
	Prop2 string
}

func main() {
	var client *elastic.Client
	hostAddr := "" // Elasticsearch host IP address
	client, _ = elastic.NewClient(elastic.SetSniff(false), elastic.SetURL(fmt.Sprintf("http://%s:9200/", hostAddr)))
	ctx := context.Background()
	indexName := "test"
	if exists, _ := client.IndexExists(indexName).Do(ctx); !exists {
		fmt.Println("CreateIndex", indexName)
		if _, err := client.CreateIndex(indexName).Do(ctx); err != nil {
			log.Printf("elasticsearch CreateIndex err: %s", err.Error())
		}
	}
	i := 1
	bulkRequest := client.Bulk()
	for {
		if i == 60001 {
			break
		}
		temp := TestStruct{Prop1: i + 1, Prop2: strconv.Itoa(i)}
		req := elastic.NewBulkIndexRequest().Index(indexName).Type("TestStruct").Id(temp.Prop2).Doc(temp)
		bulkRequest = bulkRequest.Add(req)
		i++
	}
	bulkRequest.Do(ctx)
	log.Println("Bulk request is done")
	log.Println("Scroll query starting")
	scrollSize := 10000
	scroll := client.Scroll()
	q := scroll.KeepAlive("5m").Size(scrollSize).Type("TestStruct").
		Query(
			elastic.NewBoolQuery().Must(
				elastic.NewRangeQuery("Prop1").Lte(50001),
			),
		)
	t0 := time.Now()
	t1 := time.Now()
	for {
		searchResult, err := q.Do(ctx)
		actualTook := time.Now().Sub(t1)
		if err == nil {
			tookInMillis := searchResult.TookInMillis
			log.Printf("Query Actual Time: %+v and TookInMillis in response: %+vms \n", actualTook, tookInMillis)
			for _, hit := range searchResult.Hits.Hits {
				var ts *TestStruct
				json.Unmarshal(*hit.Source, &ts)
			}
		} else if err == io.EOF {
			log.Printf("Total time %+v\n", time.Now().Sub(t0))
			break
		} else {
			log.Printf("Load err: %s", err.Error())
			break
		}
		t1 = time.Now()
	}
}
```
Logs for scrollSize = 10000
```
Query Actual Time: 81.998614ms and TookInMillis in response: 25ms 
Query Actual Time: 77.475781ms and TookInMillis in response: 17ms 
Query Actual Time: 74.166535ms and TookInMillis in response: 19ms 
Query Actual Time: 77.226671ms and TookInMillis in response: 17ms 
Query Actual Time: 69.096837ms and TookInMillis in response: 15ms 
Total time 448.968583ms
```
Logs for scrollSize = 5000
```
Query Actual Time: 50.218901ms and TookInMillis in response: 23ms 
Query Actual Time: 47.622721ms and TookInMillis in response: 14ms 
Query Actual Time: 36.855242ms and TookInMillis in response: 11ms 
Query Actual Time: 45.524261ms and TookInMillis in response: 15ms 
Query Actual Time: 50.120616ms and TookInMillis in response: 15ms 
Query Actual Time: 42.499079ms and TookInMillis in response: 12ms 
Query Actual Time: 43.016177ms and TookInMillis in response: 16ms 
Query Actual Time: 46.79838ms and TookInMillis in response: 17ms 
Query Actual Time: 42.143692ms and TookInMillis in response: 14ms 
Query Actual Time: 54.655742ms and TookInMillis in response: 16ms 
Total time 558.737555ms
```
So is the difference between 'Query Actual Time' and 'TookInMillis in response' expected? It is more than 3 times sometime.
In reality, I have a struct with many more properties and some of them are themselves are struct. So the difference between actual time and TookInMillis is much more in my case.

**Comment by rohanil** [comment] 2017-09-26 15:53
I tried it on elasticsearch's python client and it seems the result is more or less similar. Actually, python client seems to take more time for above case. The script is below and logs follow it.
```
from elasticsearch import Elasticsearch
import datetime

es = Elasticsearch(['http://cst-es-price:9200'])

page = es.search(
        index = 'test',
        doc_type = 'TestStruct',
        scroll = '5m',
        size = 10000,
        body = {"query": {"range": {"Prop1": {"lte": 50001}}}}
)
sid = page['_scroll_id']
scroll_size = page['hits']['total']

# Start scrolling
print "Scrolling ..."
while (scroll_size > 0):
        t0 = datetime.datetime.utcnow()
        page = es.scroll(scroll_id = sid, scroll = '5m')
        actual_time = (datetime.datetime.utcnow() - t0)
        # Update the scroll ID
        sid = page['_scroll_id']
        scroll_size = len(page['hits']['hits'])
        print "Actual Time: " + str(actual_time.microseconds/1000) + "ms Took in ES response: " + str(page['took']) + "ms"
```
Logs
```
Actual Time: 92ms Took in ES response: 45ms
Actual Time: 84ms Took in ES response: 39ms
Actual Time: 94ms Took in ES response: 39ms
Actual Time: 85ms Took in ES response: 39ms
Actual Time: 5ms Took in ES response: 1ms
```
But apparently, `search` API of python client is pretty fast. I don't know how it manages the window size because if I use search API of go client, it throws error with message to increase [index.max_result_window] . But the request took around 3ms which was pretty fast.
```
es.search(index="test", doc_type="TestStruct", body={"query": {"range": {"Prop1": {"lte": 50001}}}})
```

**Comment by rohanil** [comment] 2017-10-11 12:35
@olivere I face this issue with BulkService request as well. In my case, I send 17K docs of 2MB size to same index and the difference between `BulkResponse.Took` and actual time taken by `BulkService.Do()` is around 1 sec. I can not reduce number of docs to send in one request as it reduces performance of ES store so the difference is reduced but overall time taken is increased. Do you think it is also serialization/deserialization extra time? Is it the issue on ES side then?

**Comment by olivere** [comment] 2017-10-11 12:57
This is definitely a serialization/deserialization issue. There is the long-standing #415 which raised a similar issue already in the context of streaming HTTP requests. I didn't have the time to look into this due to my day job.

**Comment by olivere** [comment] 2017-10-13 07:23
@rohanil I made a test some time ago (2.x) to find out how document size affects indexing performance. I can't remember all the details, but in a nutshell, it was that larger documents generally led to worse and worse performance, not only in serialization/deserialization on the Go side but also on the server side. That might have changed in later versions, but I doubt it.

This issue turned largely into a discussion, which we could do better on the Gophers Slack elasticsearch channel. There's nothing really actionable, so I'll close it for now. If you see anything actionable, turn it into a task and feel free to create a new issue.

**Closed by olivere** 2017-10-13 07:23 UTC
