### ISSUE TITLE
Sort not work --search_phase_execution_exception

### ISSUE THREAD

**Issue by Michael2008S** [olivere/elastic#203] opened 2016-01-16 15:01 UTC
```go
// Search with a term query
	termQuery := elastic.NewTermQuery("user", "olivere")
	searchResult, err := client.Search().
	Index("twitter").
	Query(termQuery).
	Sort("user", true).   	// work when comments this line 
	From(0).Size(10).
	Pretty(true).
	Do()

	if err != nil {
		beego.Error(err)
	}

```

```
MichaelShiehdeMacBook-Pro:elastictest $ go run main.go
ELASTIC 2016/01/16 22:47:04 elastic: http://127.0.0.1:9200 joined the cluster
2016/01/16 22:47:04 POST /twitter/_search?pretty=true HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/3.0.18 (darwin-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

1
{
59
"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}
0


2016/01/16 22:47:04 [main.go:63] [E] elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception] 
```

but I run this query in the console is ok:
```
 {"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}
```

it give me the correct result:
```json
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "twitter",
        "_type": "tweet",
        "_id": "1",
        "_score": 1,
        "_source": {
          "User": "olivere",
          "Message": "Take Five"
        }
      }
    ]
  }
}
```

**Comment by olivere** [comment] 2016-01-16 15:06
@Michael2008S Hi. Can you please look into elasticsearch log file for more information? If the query on the console it exactly the same as the console you paste on the command line, I can't see why it won't work.

**Comment by Michael2008S** [comment] 2016-01-16 15:09
ElasticSearch 2.1.1 log:
```
[2016-01-16 22:47:04,569][DEBUG][action.search.type       ] [T-Ray] [twitter][4], node[tS7vXWtuTHOi6BSZSoOCuA], [P], v[2], s[STARTED], a[id=dvHZWoKPRziW4lwgATrZlA]: Failed to execute [org.elasticsearch.action.search.SearchRequest@2ee2251e] lastShard [true]
RemoteTransportException[[T-Ray][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
Caused by: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:848)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:651)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:617)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[No mapping found for [user] in order to sort on]
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:215)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:189)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:87)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:831)
	... 10 more
[2016-01-16 22:47:04,569][DEBUG][action.search.type       ] [T-Ray] [twitter][1], node[tS7vXWtuTHOi6BSZSoOCuA], [P], v[2], s[STARTED], a[id=tcwe4wBXQIO58FK_GWbQlQ]: Failed to execute [org.elasticsearch.action.search.SearchRequest@2ee2251e] lastShard [true]
RemoteTransportException[[T-Ray][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
Caused by: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:848)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:651)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:617)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[No mapping found for [user] in order to sort on]
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:215)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:189)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:87)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:831)
	... 10 more
[2016-01-16 22:47:04,569][DEBUG][action.search.type       ] [T-Ray] [twitter][0], node[tS7vXWtuTHOi6BSZSoOCuA], [P], v[2], s[STARTED], a[id=CO8OdYRbR3OruANL7TzPZQ]: Failed to execute [org.elasticsearch.action.search.SearchRequest@2ee2251e] lastShard [true]
RemoteTransportException[[T-Ray][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
Caused by: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:848)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:651)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:617)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[No mapping found for [user] in order to sort on]
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:215)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:189)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:87)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:831)
	... 10 more
[2016-01-16 22:47:04,569][DEBUG][action.search.type       ] [T-Ray] [twitter][3], node[tS7vXWtuTHOi6BSZSoOCuA], [P], v[2], s[STARTED], a[id=Gy5GMuAuS7WR07t0O_cSBg]: Failed to execute [org.elasticsearch.action.search.SearchRequest@2ee2251e] lastShard [true]
RemoteTransportException[[T-Ray][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
Caused by: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:848)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:651)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:617)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[No mapping found for [user] in order to sort on]
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:215)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:189)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:87)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:831)
	... 10 more
[2016-01-16 22:47:04,569][DEBUG][action.search.type       ] [T-Ray] [twitter][2], node[tS7vXWtuTHOi6BSZSoOCuA], [P], v[2], s[STARTED], a[id=iNoGYZ74SIK4kQg1alnElA]: Failed to execute [org.elasticsearch.action.search.SearchRequest@2ee2251e]
RemoteTransportException[[T-Ray][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
Caused by: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:848)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:651)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:617)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[No mapping found for [user] in order to sort on]
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:215)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:189)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:87)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:831)
	... 10 more
[2016-01-16 22:47:04,627][DEBUG][action.search.type       ] [T-Ray] All shards failed for phase: [query]
RemoteTransportException[[T-Ray][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
Caused by: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on];
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:848)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:651)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:617)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[No mapping found for [user] in order to sort on]
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:215)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:189)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:87)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:831)
	... 10 more
[2016-01-16 22:47:04,629][INFO ][rest.suppressed          ] /twitter/_search Params: {pretty=true, index=twitter}
Failed to execute phase [query], all shards failed; shardFailures {[tS7vXWtuTHOi6BSZSoOCuA][twitter][0]: RemoteTransportException[[T-Ray][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on]; }{[tS7vXWtuTHOi6BSZSoOCuA][twitter][1]: RemoteTransportException[[T-Ray][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on]; }{[tS7vXWtuTHOi6BSZSoOCuA][twitter][2]: RemoteTransportException[[T-Ray][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on]; }{[tS7vXWtuTHOi6BSZSoOCuA][twitter][3]: RemoteTransportException[[T-Ray][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on]; }{[tS7vXWtuTHOi6BSZSoOCuA][twitter][4]: RemoteTransportException[[T-Ray][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"query":{"term":{"user":"olivere"}},"size":10,"sort":[{"user":{"order":"asc"}}]}]]; nested: SearchParseException[No mapping found for [user] in order to sort on]; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:228)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:174)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[No mapping found for [user] in order to sort on]
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:215)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:189)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:87)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:831)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:651)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:617)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	... 3 more
```

**Comment by olivere** [comment] 2016-01-16 15:12
It says

```
No mapping found for [user] in order to sort on
```

where in your mapping you have

```
"_source": {
  "User": "olivere",
  "Message": "Take Five"
}
```

Can you try to sort on `User` (with an uppercase `U`)?

**Comment by Michael2008S** [comment] 2016-01-16 15:13
May be I found what case this problem:  (the "user" in the code ,and the field "User" in elasticsearch)

```go
 Sort("user", true).
```

```json
        "_source": {
          "User": "olivere",
          "Message": "Take Five"
        }
```

**Comment by Michael2008S** [comment] 2016-01-16 15:14
ok.I see. thanks

**Comment by olivere** [comment] 2016-01-16 15:18
Can you check if that's the issue and then close it if resolved? Thank you.

**Closed** 2016-01-16 15:25 UTC

**Comment by jayncoke** [comment] 2017-01-20 18:30
I'm getting this error. The field I sort on matches the field in the index ("Name"). Closest I can get to figuring it out was the answer to this: http://stackoverflow.com/questions/17051709/no-mapping-found-for-field-in-order-to-sort-on-in-elasticsearch. However, I have no idea how to set "ignore_unmapped" for the sort.

Here's my call: 
`
        query := elastic.NewBoolQuery()
        query = query.Must(elastic.NewMatchQuery("Name", "foobar"))
	searchResult, err := esClient.Search().
		Query(query).
		Sort("Name", true).
		From(0).Size(20).
		Pretty(true).
		Do()
`

I see this error in my elasticsearch log:

> SearchParseException[No mapping found for [Name] in order to sort on];
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:873)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:377)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[No mapping found for [Name] in order to sort on]
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:213)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:187)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:85)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:856)

**Comment by olivere** [comment] 2017-01-20 21:06
@jayncoke This typically happens if you use an index without a mapping. If you really want to do this, you may use the `"ignore_unmapped"` by using `FieldSort`. [Here is an example](https://github.com/olivere/elastic/blob/release-branch.v5/sort_test.go#L141-L161) of how to construct such a sorter.

**Comment by olivere** [comment] 2017-01-20 21:12
@jayncoke [Related issue](https://discuss.elastic.co/t/searchparseexception-no-mapping-found/48590/2). Your query doesn't specify any index/type, so you search all of the indices/types. ES doesn't know what to do when it doesn't find a `"Name"` field in one of those indices.

**Comment by jayncoke** [comment] 2017-01-23 16:41
@olivere Thanks for the response! I added the index to search and it looks like this works:

```
esClient.Search("searchIndexName").
		Query(query).
```

over this:

```
esClient.Search().Index("searchIndexName").
		Query(query).
```

The latter one with the Index() call gives me the aforementioned error. Should I be using that to search a specific index or passing the index name to Search() is fine?

**Comment by olivere** [comment] 2017-01-23 17:49
@jayncoke The former is simply a shortcut for the latter: See [here](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L1282-L1285) and [here](https://github.com/olivere/elastic/blob/release-branch.v5/search.go#L61-L68).
